### ISSUE TITLE
Release of console is not a standard treatment

### ISSUE THREAD

**Issue by lucabrag** [jackblun/leisure_git#14]
Hi guys,

Suppose we want to use a generalized DID as a strategy. If I understand it correctly, the treatment is administered to certain people after a certain date and not administered to anybody before that date. 

Console releases doesn't quite work like that. It's not that as soon as a console is released everybody buys it. Maybe people wait to buy it. Kids may have to wait till christmas for their parents to buy it. Adults may have to wait till the end of the month to get a paycheck with which to buy it. Etc.

I'm sure there are ways to analyze experiments in which the treatment starts being administered after a certain date but it reaches people in the target population at different times. Maybe that's the right way of looking at it

**Comment by tomzohar1** [comment]
I believe this should be addressed by using the choice of time span using the ridge regression
