### ISSUE TITLE
Generalized DID

### ISSUE THREAD

**Issue by tomzohar1** [jackblun/leisure_git#9]
Adopt either a G-DID approach (as discussed in Labor class) or a similar concept but for one diff (thus a generalized event study).

**Comment by jackblun** [comment]
I've coded up some G-DiD stuff, both trying leisure and work activities as the outcome. Graphically, we can see that with our sample sizes, leisure is extremely volatile. Work activities is perhaps a bit more promising.

I've so far been using men 30-39 as a control group for all men 20-29, but there is no good objective reason to choose these groups.

**Comment by jackblun** [comment]
Have updated this. Now I use all men 30-55 as a control group, closer to A&H

**Comment by lucabrag** [comment]
Generalized event study has issues it there is seasonality. Most of our consoles are released in late November. A generalized event study may simply pick up on seasonality. Generalized DID seems better

**Comment by tomzohar1** [comment]
Since we don't have an obvious control group but still want to perform a G-DID, we should use synthetic controls. This will require significantly more work but then will also have a methodological contribution (I never heard of anyone using synthetic controls for G-DID, just a DID).
